name: portfolio_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  args: ^2.0.0
  http: ^0.13.5
  shelf: ^1.1.0
  shelf_cors_headers: ^0.1.4
  shelf_router: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
